<Project DefaultTargets="Build" xmlns="http://schemas.microsoft.com/developer/msbuild/2003" TreatAsLocalProperty="OutDir;Configuration">

  <PropertyGroup>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
    <Configuration Condition=" '$(Configuration)' == '' ">Debug</Configuration>

    <RepoRoot>$(MSBuildThisFileDirectory)</RepoRoot>

    <ArtifactsPath>$(RepoRoot)artifacts\</ArtifactsPath>
    <BinPath>$(ArtifactsPath)bin\</BinPath>
    <ObjPath>$(ArtifactsPath)obj\</ObjPath>

    <OutputPath>$(BinPath)$(MSBuildProjectName)\$(Configuration)</OutputPath>
    <BaseIntermediateOutputPath>$(ObjPath)$(MSBuildProjectName)\$(Configuration)</BaseIntermediateOutputPath>
  </PropertyGroup>

</Project>