<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net472</TargetFramework>
    <UseWpf>true</UseWpf>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="AvalonDock-1.x" />
    <PackageReference Include="System.Composition" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\PolyFills\PolyFills.csproj" />
    <ProjectReference Include="..\ZDebug.Core\ZDebug.Core.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Resource Include="Images\*.png" />
  </ItemGroup>

</Project>
