<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0-windows7.0</TargetFramework>
    <UseWpf>true</UseWpf>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Dirkster.AvalonDock" />
    <PackageReference Include="Dirkster.AvalonDock.Themes.VS2013" />
    <PackageReference Include="System.Composition" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\ZDebug.Core\ZDebug.Core.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Resource Include="Images\*.png" />
  </ItemGroup>

</Project>
