namespace ZDebug.Compiler.CodeGeneration
{
    internal enum OpcodeGeneratorKind
    {
        Add,
        And,
        ArtShift,
        Dec,
        DecChk,
        Div,
        Inc,
        IncChk,
        Je2Op,
        JeMultiOp,
        Jin,
        Jg,
        Jl,
        Jump,
        Jz,
        LogShift,
        Mod,
        Mul,
        Not,
        Or,
        Ret,
        RetPopped,
        Rfalse,
        Rtrue,
        Sub,
        Test,
    }
}
