<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net472</TargetFramework>
    <OutputType>WinExe</OutputType>
    <UseWpf>true</UseWpf>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="System.Composition" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\ZDebug.IO\ZDebug.IO.csproj" />
    <ProjectReference Include="..\ZDebug.UI.Core\ZDebug.UI.Core.csproj" />
  </ItemGroup>

</Project>
