<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net472</TargetFramework>
    <OutputType>Exe</OutputType>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\PolyFills\PolyFills.csproj" />
    <ProjectReference Include="..\ZDebug.Compiler\ZDebug.Compiler.csproj" />
  </ItemGroup>

</Project>
